apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openclaw
  namespace: argo-cd
spec:
  project: spof-cluster
  sources:
    - repoURL: "https://github.com/marcleibold/openclaw.git"
      targetRevision: HEAD
      path: resources
  destination:
    server: "https://kubernetes.default.svc"
    namespace: openclaw
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
