---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openclaw-secrets
  namespace: openclaw
spec:
  encryptedData:
    MINIMAX_API_KEY: AgCgg0KBNKTJ6dJ9WFieJPW4HHJ7GYQPuFM84L9aQLaW3s5DLWGEV7xL79XBmqCKK9aOkR6Xk3pSJuoSsDrri+Yl/QO1AzomlTEZ/e2IDQCeiESBjXpnqtfitmLqALHqOvN3OFMlACQehPuPQYFcKA8l+zQs6gvCMwJFwxyWMozgCv9DnjDyRH7BOmXqc7b9wsatljmPfWCex95nLqLyPPqLJC0OX9UMmYtW7rCYV1yoom3YaebYBWxz9k0LRVfioO/QGVR/xNA+Ud1OB1t31mwl36ZY2XtLlHRW9BiaxnNZcq9FVdfycJxC5zFWqLsdqgKseCUekUt6V+Gmu1ooWtp3zB4oiDvKSCvgy5fZrytt1SvuNVEF3ZGTEepx/+YbSOk/n62qamTI+UusjEkSxr12gTsnhDcRI6oLdWuSE8UEVYO3wTYLsR/5gbFB0uEv9cqh2lyM88TbDxB/aLhfmG+Y4Rwo+9lLTiai5PKcNPP76ff43az1P0PUvfrtnAQ98EgelAMSgZKtiuhjxaGDYw3vw6vojP/xwcHVwOnouMSp24ctYDHy49eqAtJIqp61TDkSD3cSsQhSZ5+ApJ9enHkraNRrDs2KLDHK4d1RV3yobKww/E0/wJqpNMRO4hhuN50i8FJUCBwz9CdI8/kjHZjuMpIUoz3mSUXqcCNxF9SB4I4RI/0lnF2v4WvStseOIGPJDR1LkLQvvKxm6Rx/RsItEEIpYCpzmVOXiRMbBkOV9u9VcCZEpkcH21yCH5SahfUJyQoxfyaofAkvAPWKMKDBorHeRwriloqQ1wEU55/euMfYRrb/LGqOOb4T7uc+JOO3Lsg0MfXdxf6V8UaeF+McLhFrK+0AlVBGlcI7/g==
    OPENCLAW_GATEWAY_TOKEN: AgAFnongnueA63U1tpvEXVWkz+dYyhJRzrswvjZStqLDxBeaA75HsYQ4gn+GRM+4aiH4Zw6gUQugQd2bIDNOdUUQ12G4kaupCrxBs9g3QMmA9AQsOhHUV7xJSSkx7sRTYmmSMAaNvQHtoBZO/VMY3EEeGRjo15eAMBDP84lh7OrpJArH0ErTBSWfSzQnbW+87FxpvblNr+VAASHO027Nax5vPrnTYlwtHVusSjRueq4cyZ5ixYhG3eMcBK4gypj+nWMB93H3c6cqipt7hTiWujSS1pwjzIqWP8LNjzE7VjFbLgYqqfgPiU68hf+r9EggObmXnLMHIx/yy6W2GZ4MGjaQXQW0s+WKXA50E9IRWKR4rV97RlbQU7xseiGn01viQwA2fDZsrI7HEMFrbL5HRFDl/kjoumU26vM+O+cZ/iCFx9GLuLbHN5+Hxm8NuIzZ6L01IytvMsC5eBuHJICHtNfpUqQtfjfM0suF/25C6bg4Rav6+8KuWgmeWBSWzwsAhj0JTv4fvTO10VWQORbJ7S47A+DY3Irfm+QD4qVHRmO5vdV7xR47TjnTkomtJsPXBl0jmDhQIXNlucY9fG+Tl7yp21qS87Zj0G7u3vkgYmDTWRu7nycumMJk5d8gYOtJh/PHmGZlQ7BQxiDEsP4HrBgSgOP8GQVFkU3WFO70R/kz4axIe1FzAMjly54dmdRUe6qUXJBsFg/Xt0rDhuEqY3PN6qX7Y2KNPRay1zpTIP2U/CeIGCBaStbGcZxCxzwbTY8=
  template:
    metadata:
      creationTimestamp: null
      name: openclaw-secrets
      namespace: openclaw
