apiVersion: v1
kind: Service
metadata:
  name: openclaw
  namespace: openclaw
  labels:
    app: openclaw
  annotations:
    metallb.io/loadbalancerIP: 192.168.178.129
spec:
  type: LoadBalancer
  selector:
    app: openclaw
  ports:
    - name: gateway
      port: 18789
      targetPort: 18789
      protocol: TCP
    - name: syncthing
      port: 8384
      targetPort: 8384
      protocol: TCP